CREATE TABLE IF NOT EXISTS `m_companies` (
  `company_id`                  bigint(20)   NOT NULL AUTO_INCREMENT COMMENT '企業ID',
  `companyname`                 varchar(128) DEFAULT NULL COMMENT '企業名',
  `companyname_kana`            varchar(128) DEFAULT NULL COMMENT '企業名カナ',
  `pref_id`                     int          DEFAULT NULL COMMENT '都道府県',
  `zip_code`                    varchar(7)   CHARACTER SET ascii NOT NULL COMMENT '郵便場号',
  `city_code`                   varchar(50)  CHARACTER SET ascii NOT NULL COMMENT '市区町村',
  `address`                     varchar(128) NOT NULL COMMENT '市区町村以下',
  `email_address`               varchar(256) CHARACTER SET ascii NOT NULL COMMENT 'emailアドレス',
  `tel`                         varchar(20)  CHARACTER SET ascii NOT NULL COMMENT '電話番号',
  `fax`                         varchar(20)  CHARACTER SET ascii NOT NULL COMMENT 'fax',
  `responsible_first_name`      varchar(20)  DEFAULT NULL COMMENT '担当者(名)',
  `responsible_last_name`       varchar(20)  DEFAULT NULL COMMENT '担当者(姓)',
  `responsible_first_name_kana` varchar(20)  DEFAULT NULL COMMENT '担当者カナ(名)',
  `responsible_last_name_kana`  varchar(20)  DEFAULT NULL COMMENT '担当者カナ(姓)',
  `active_flag`                 boolean      DEFAULT NULL COMMENT 'アクティブフラグ',
  `updated_id`                  int(11)      DEFAULT NULL COMMENT '更新者ID',
  `registed`                    datetime     DEFAULT NULL COMMENT '登録日時',
  `updated`                     datetime     DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_id`),
  INDEX (`companyname`),
  INDEX (`companyname_kana`),
  INDEX (`active_flag`),
  INDEX (`updated_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='企業マスタ';
