<style>
#header_rightarea #h_navi ul{
    float: right;
    width: auto;
}
</style>
<div id="headerarea" class="inner">
	<div id="header">
		<div id="header_logoarea" class="box14">
			<div class="summary">
				<a href="/">美容・治療・リラクゼーション求人のチューズ トップ</a>
			</div>
			<div id="logo" class="box9">
				<a href="<?= $this->url_header_lnk; ?>" title=""><img
					src="<?php echo $this->urlImg; ?>/toppage/logo.png" alt="" />
				</a>
			</div>
			<!-- #logo -->
			<h1>
				<?= $this->str_header_title; ?>
			</h1>
		</div>
		<!-- /#headerlogoarea -->
		<div id="header_rightarea" class="box10">
            <div id="h_navi">
                <ul>
                    <li id="h_navi01"><a href="/info/faq">よくある質問</a> </li>
                    <li id="h_navi03"><a href="/my-page/register">新規会員登録</a></li>
                    <li id="h_navi04"><a href="/login">ユーザーログイン</a></li>
                </ul>
            </div>
			<!-- /#h_navi -->
			<div id="header_icon">
				<img src="<?php echo $this->urlImg; ?>/toppage/header_right_img.gif"
					alt="" />
			</div>
			<!-- /#header_icon -->

		</div>
		<!-- /#header_rightarea -->
	</div>
	<!-- /#header -->
</div>
<!-- /#headerarea -->
