<style>
    dt, dd {
        float:left;
        margin:0;
        margin-top:20px;
        padding:0;
    }

    dt {
        clear: both;
        width:150px;
        margin-left: 100px;
    }
    
    dd {
    }
</style>
<dl>
    <dt><a href="/crawl/shop/">登録君</a></dt>
    <dd><a href="/help/crawl_shop">help you</a></dd>
    <dt><a href="/shop/list">店舗一覧</a></dt>
    <dd><a href="/help/shop_add">help you</a></dd>
    <dt><a href="/shop/add">店舗登録ちゃん</a></dt>
    <dd><a href="/help/shop_add">help you</a></dd>
</dl>
