<style>
    #sub #touroku_form_box a {
        text-decoration:underline;
    }
</style>
<div id="sub">
	<div id="touroku_form_box">
		<div class="logo_box01">
			<img src="/pc/images/toppage/logo.png" alt="" />
		</div>
		<div class="kousin">最終更新7/2日</div>
		<ul>
			<li>求人数<span class="counter01">000,000</span><span class="font01">件</span></li>
		</ul>
		<form method="post" action="#">
			<table width="198">
				<tr>
					<td colspan="2"><div class="user_login01">
							<img src="/pc/images/toppage/t_form_icon03.gif" width="197"
								alt="" />
						</div>
					</td>
				</tr>
				<tr>
					<td colspan="2">ご登録のメールアドレス<br />
					<input type="text" name="#" class="text_box01" />
					</td>
				</tr>
				<tr>
					<td colspan="2">パスワード<br />
					<input type="text" name="#" class="text_box01" />
					</td>
				</tr>
				<tr>
					<td width="99"><input type="button" value="ログイン"
						class="user_login02" />
					</td>
					<td width="99"><input type="button" value="会員登録"
						class="user_login03" onclick="window.location='/my-page/regist'"/>
					</td>
				</tr>
				<tr>
					<td colspan="2"><a href="/my-page/lostpass">パスワードを忘れた方はこちら&gt&gt</a></td>
				</tr>
			</table>
		</form>
	</div>
</div>
<!--/#sub -->
