<div id="sub_shop">
	<div id="shop_touroku_form_box">
		<div class="shop_kousin">最終更新7/2日</div>
		<ul>
			<li>求人数<span class="shop_counter01">000,000</span><span
				class="font01">件</span>
			</li>
			<li>登録数<span class="shop_counter01">000,000</span><span
				class="font01">人</span>
			</li>
		</ul>
		<form method="post" action="#">
			<table>
				<tr>
					<td colspan="2">
						<div class="shop_user_login01">
							<img src="/pc/images/toppage/t_form_icon03.gif" width="165"
								alt="" />
						</div>
					</td>
				</tr>
				<tr>
					<td colspan="2">ご登録のメールアドレス<br /> <input type="text" name="#"
						class="shop_text_box01" />
					</td>
				</tr>
				<tr>
					<td colspan="2">パスワード<br /> <input type="text" name="#"
						class="shop_text_box01" />
					</td>
				</tr>
				<tr>
					<td colspan="2"><input type="checkbox" name="#" value="" />次回からは自動的にログイン</td>
				</tr>
				<tr>
					<td><input type="button" value="ログイン" class="shop_user_login02" />
					</td>
					<td><input type="button" value="会員登録" class="shop_user_login03" />
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>
